export const GROCERY_PRODUCTS = [
  // Dairy & Eggs
  { name: "Full Cream Milk 2L", price: 2.90, category: "Dairy" },
  { name: "Full Cream Milk 3L", price: 4.50, category: "Dairy" },
  { name: "Skim Milk 2L", price: 2.90, category: "Dairy" },
  { name: "Oat Milk 1L", price: 4.50, category: "Dairy" },
  { name: "Almond Milk 1L", price: 3.50, category: "Dairy" },
  { name: "Soy Milk 1L", price: 2.50, category: "Dairy" },
  { name: "Thickened Cream 300ml", price: 3.00, category: "Dairy" },
  { name: "Sour Cream 300ml", price: 3.20, category: "Dairy" },
  { name: "Greek Yoghurt 1kg", price: 7.00, category: "Dairy" },
  { name: "Chobani Yoghurt 170g", price: 2.50, category: "Dairy" },
  { name: "Natural Yoghurt 500g", price: 3.50, category: "Dairy" },
  { name: "Butter 500g", price: 5.50, category: "Dairy" },
  { name: "Tasty Cheese Block 500g", price: 6.50, category: "Dairy" },
  { name: "Shredded Mozzarella 500g", price: 6.00, category: "Dairy" },
  { name: "Parmesan Wedge 250g", price: 7.50, category: "Dairy" },
  { name: "Cream Cheese 250g", price: 3.50, category: "Dairy" },
  { name: "Haloumi 180g", price: 5.50, category: "Dairy" },
  { name: "Free Range Eggs 12pk", price: 6.50, category: "Dairy" },
  { name: "Cage Free Eggs 12pk", price: 5.50, category: "Dairy" },
  { name: "Free Range Eggs 6pk", price: 4.00, category: "Dairy" },

  // Bread & Bakery
  { name: "White Bread Loaf", price: 3.20, category: "Bakery" },
  { name: "Wholemeal Bread Loaf", price: 3.50, category: "Bakery" },
  { name: "Sourdough Loaf", price: 5.50, category: "Bakery" },
  { name: "Multigrain Bread", price: 3.80, category: "Bakery" },
  { name: "Wraps 8pk", price: 3.50, category: "Bakery" },
  { name: "Pita Bread 5pk", price: 3.00, category: "Bakery" },
  { name: "Burger Buns 6pk", price: 3.50, category: "Bakery" },
  { name: "Crumpets 6pk", price: 3.20, category: "Bakery" },
  { name: "English Muffins 6pk", price: 3.50, category: "Bakery" },
  { name: "Croissants 4pk", price: 5.00, category: "Bakery" },
  { name: "Bagels 4pk", price: 4.50, category: "Bakery" },

  // Meat & Seafood
  { name: "Chicken Breast 1kg", price: 12.00, category: "Meat" },
  { name: "Chicken Thigh 1kg", price: 9.00, category: "Meat" },
  { name: "Chicken Drumsticks 1kg", price: 5.50, category: "Meat" },
  { name: "Beef Mince 500g", price: 8.00, category: "Meat" },
  { name: "Beef Mince 1kg", price: 14.00, category: "Meat" },
  { name: "Beef Steak Scotch Fillet", price: 18.00, category: "Meat" },
  { name: "Beef Sausages 8pk", price: 7.50, category: "Meat" },
  { name: "Lamb Chops 500g", price: 12.00, category: "Meat" },
  { name: "Lamb Mince 500g", price: 9.00, category: "Meat" },
  { name: "Pork Chops 500g", price: 8.50, category: "Meat" },
  { name: "Bacon Rashers 250g", price: 5.50, category: "Meat" },
  { name: "Bacon Short Cut 500g", price: 9.00, category: "Meat" },
  { name: "Ham Sliced 200g", price: 4.50, category: "Meat" },
  { name: "Salami Sliced 100g", price: 4.00, category: "Meat" },
  { name: "Salmon Fillets 400g", price: 14.00, category: "Meat" },
  { name: "Prawns Raw 500g", price: 15.00, category: "Meat" },
  { name: "Barramundi Fillets 400g", price: 12.00, category: "Meat" },
  { name: "Fish Fingers 24pk", price: 6.50, category: "Meat" },
  { name: "Tuna Steaks 400g", price: 13.00, category: "Meat" },

  // Fruit
  { name: "Bananas 1kg", price: 3.50, category: "Fruit" },
  { name: "Apples Royal Gala 1kg", price: 4.50, category: "Fruit" },
  { name: "Apples Pink Lady 1kg", price: 5.50, category: "Fruit" },
  { name: "Oranges Navel 1kg", price: 4.00, category: "Fruit" },
  { name: "Strawberries 250g", price: 3.50, category: "Fruit" },
  { name: "Blueberries 125g", price: 4.00, category: "Fruit" },
  { name: "Raspberries 125g", price: 5.00, category: "Fruit" },
  { name: "Grapes Green 500g", price: 5.00, category: "Fruit" },
  { name: "Watermelon Seedless Half", price: 5.50, category: "Fruit" },
  { name: "Avocados 3pk", price: 5.00, category: "Fruit" },
  { name: "Avocado Single", price: 2.50, category: "Fruit" },
  { name: "Lemons 1kg", price: 5.00, category: "Fruit" },
  { name: "Limes 4pk", price: 3.00, category: "Fruit" },
  { name: "Mangoes Each", price: 3.00, category: "Fruit" },
  { name: "Kiwi Fruit 4pk", price: 3.50, category: "Fruit" },
  { name: "Pear Packham 1kg", price: 4.50, category: "Fruit" },

  // Vegetables
  { name: "Potatoes Washed 2kg", price: 4.50, category: "Vegetables" },
  { name: "Sweet Potato 1kg", price: 4.00, category: "Vegetables" },
  { name: "Onions Brown 1kg", price: 2.50, category: "Vegetables" },
  { name: "Onion Red Each", price: 1.50, category: "Vegetables" },
  { name: "Garlic 3pk", price: 2.50, category: "Vegetables" },
  { name: "Ginger 100g", price: 1.50, category: "Vegetables" },
  { name: "Tomatoes 500g", price: 4.50, category: "Vegetables" },
  { name: "Cherry Tomatoes 250g", price: 3.50, category: "Vegetables" },
  { name: "Cucumber Lebanese 3pk", price: 3.00, category: "Vegetables" },
  { name: "Capsicum Red Each", price: 2.50, category: "Vegetables" },
  { name: "Capsicum Green Each", price: 2.00, category: "Vegetables" },
  { name: "Broccoli Each", price: 3.50, category: "Vegetables" },
  { name: "Cauliflower Each", price: 4.00, category: "Vegetables" },
  { name: "Carrots 1kg", price: 2.00, category: "Vegetables" },
  { name: "Zucchini Each", price: 2.00, category: "Vegetables" },
  { name: "Mushrooms Cup 200g", price: 3.50, category: "Vegetables" },
  { name: "Mushrooms Button 400g", price: 5.00, category: "Vegetables" },
  { name: "Spinach Baby 120g", price: 3.50, category: "Vegetables" },
  { name: "Mixed Salad 120g", price: 3.50, category: "Vegetables" },
  { name: "Rocket 120g", price: 3.50, category: "Vegetables" },
  { name: "Spring Onions Bunch", price: 2.00, category: "Vegetables" },
  { name: "Corn Cobs 4pk", price: 4.50, category: "Vegetables" },
  { name: "Beans Green 250g", price: 4.00, category: "Vegetables" },
  { name: "Celery Bunch", price: 3.50, category: "Vegetables" },
  { name: "Lettuce Iceberg", price: 2.50, category: "Vegetables" },
  { name: "Lettuce Cos", price: 2.50, category: "Vegetables" },
  { name: "Eggplant Each", price: 3.00, category: "Vegetables" },
  { name: "Pumpkin Butternut Half", price: 3.50, category: "Vegetables" },

  // Pantry
  { name: "Basmati Rice 1kg", price: 4.00, category: "Pantry" },
  { name: "Jasmine Rice 5kg", price: 12.00, category: "Pantry" },
  { name: "Brown Rice 1kg", price: 3.50, category: "Pantry" },
  { name: "Pasta Spaghetti 500g", price: 2.00, category: "Pantry" },
  { name: "Pasta Penne 500g", price: 2.00, category: "Pantry" },
  { name: "Pasta Fusilli 500g", price: 2.00, category: "Pantry" },
  { name: "Pasta Sauce Tomato & Basil", price: 3.50, category: "Pantry" },
  { name: "Pasta Sauce Bolognese", price: 3.50, category: "Pantry" },
  { name: "Passata 700ml", price: 2.50, category: "Pantry" },
  { name: "Diced Tomatoes 400g", price: 1.50, category: "Pantry" },
  { name: "Coconut Milk 400ml", price: 2.00, category: "Pantry" },
  { name: "Coconut Cream 400ml", price: 2.00, category: "Pantry" },
  { name: "Olive Oil Extra Virgin 500ml", price: 8.00, category: "Pantry" },
  { name: "Olive Oil 1L", price: 12.00, category: "Pantry" },
  { name: "Vegetable Oil 1L", price: 4.00, category: "Pantry" },
  { name: "Soy Sauce 500ml", price: 3.50, category: "Pantry" },
  { name: "Fish Sauce 200ml", price: 3.00, category: "Pantry" },
  { name: "Sweet Chilli Sauce 500ml", price: 3.50, category: "Pantry" },
  { name: "Tomato Sauce 500ml", price: 3.00, category: "Pantry" },
  { name: "BBQ Sauce 500ml", price: 3.50, category: "Pantry" },
  { name: "Sriracha Sauce 435ml", price: 5.00, category: "Pantry" },
  { name: "Peanut Butter Smooth 375g", price: 5.00, category: "Pantry" },
  { name: "Peanut Butter Crunchy 375g", price: 5.00, category: "Pantry" },
  { name: "Vegemite 380g", price: 6.00, category: "Pantry" },
  { name: "Nutella 400g", price: 5.50, category: "Pantry" },
  { name: "Honey 500g", price: 7.00, category: "Pantry" },
  { name: "Jam Strawberry 375g", price: 3.50, category: "Pantry" },
  { name: "Baked Beans 420g", price: 2.00, category: "Pantry" },
  { name: "Canned Tuna in Oil 425g", price: 3.50, category: "Pantry" },
  { name: "Canned Tuna in Springwater 425g", price: 3.50, category: "Pantry" },
  { name: "Chickpeas 400g", price: 1.50, category: "Pantry" },
  { name: "Kidney Beans 400g", price: 1.50, category: "Pantry" },
  { name: "Lentils Red 500g", price: 3.00, category: "Pantry" },
  { name: "Flour Plain 1kg", price: 2.00, category: "Pantry" },
  { name: "Flour Self Raising 1kg", price: 2.00, category: "Pantry" },
  { name: "Sugar White 1kg", price: 2.50, category: "Pantry" },
  { name: "Sugar Brown 500g", price: 2.50, category: "Pantry" },
  { name: "Salt Table 500g", price: 1.50, category: "Pantry" },
  { name: "Pepper Black Ground 50g", price: 3.50, category: "Pantry" },
  { name: "Stock Chicken 1L", price: 3.00, category: "Pantry" },
  { name: "Stock Beef 1L", price: 3.00, category: "Pantry" },
  { name: "Stock Vegetable 1L", price: 3.00, category: "Pantry" },
  { name: "Noodles Instant 5pk", price: 3.50, category: "Pantry" },
  { name: "Noodles Udon 440g", price: 3.00, category: "Pantry" },
  { name: "Rice Paper 200g", price: 3.50, category: "Pantry" },
  { name: "Taco Kit 12pk", price: 5.50, category: "Pantry" },
  { name: "Curry Paste Red 270g", price: 3.50, category: "Pantry" },
  { name: "Curry Paste Green 270g", price: 3.50, category: "Pantry" },

  // Breakfast & Cereal
  { name: "Weet-Bix 575g", price: 4.50, category: "Breakfast" },
  { name: "Corn Flakes 500g", price: 4.50, category: "Breakfast" },
  { name: "Muesli Toasted 750g", price: 6.00, category: "Breakfast" },
  { name: "Granola 450g", price: 6.50, category: "Breakfast" },
  { name: "Rolled Oats 1kg", price: 4.00, category: "Breakfast" },
  { name: "Quick Oats 500g", price: 3.50, category: "Breakfast" },
  { name: "Up&Go 250ml 3pk", price: 5.00, category: "Breakfast" },
  { name: "Maple Syrup 250ml", price: 6.50, category: "Breakfast" },

  // Drinks
  { name: "Orange Juice 2L", price: 5.50, category: "Drinks" },
  { name: "Apple Juice 2L", price: 4.00, category: "Drinks" },
  { name: "Coca-Cola 1.25L", price: 3.15, category: "Drinks" },
  { name: "Coca-Cola Zero 1.25L", price: 3.15, category: "Drinks" },
  { name: "Pepsi Max 1.25L", price: 2.50, category: "Drinks" },
  { name: "Sprite 1.25L", price: 3.15, category: "Drinks" },
  { name: "Sparkling Water 1L", price: 1.50, category: "Drinks" },
  { name: "Spring Water 1.5L", price: 1.00, category: "Drinks" },
  { name: "Kombucha 330ml", price: 4.00, category: "Drinks" },
  { name: "Coconut Water 1L", price: 4.50, category: "Drinks" },
  { name: "Sports Drink 600ml", price: 3.50, category: "Drinks" },
  { name: "Energy Drink 250ml", price: 3.00, category: "Drinks" },
  { name: "Beer 6pk", price: 18.00, category: "Drinks" },
  { name: "Wine Sauvignon Blanc", price: 12.00, category: "Drinks" },
  { name: "Wine Shiraz", price: 12.00, category: "Drinks" },

  // Coffee & Tea
  { name: "Coffee Beans 500g", price: 14.00, category: "Coffee" },
  { name: "Coffee Ground 500g", price: 12.00, category: "Coffee" },
  { name: "Instant Coffee 200g", price: 8.00, category: "Coffee" },
  { name: "Nespresso Capsules 10pk", price: 8.00, category: "Coffee" },
  { name: "Tea Bags Black 100pk", price: 5.00, category: "Coffee" },
  { name: "Tea Bags Green 50pk", price: 4.50, category: "Coffee" },
  { name: "Herbal Tea 20pk", price: 4.00, category: "Coffee" },

  // Snacks
  { name: "Tim Tams Original 200g", price: 3.65, category: "Snacks" },
  { name: "Tim Tams Double Coat 200g", price: 3.65, category: "Snacks" },
  { name: "Shapes BBQ 175g", price: 3.00, category: "Snacks" },
  { name: "Shapes Pizza 175g", price: 3.00, category: "Snacks" },
  { name: "Smith's Chips Original 170g", price: 4.50, category: "Snacks" },
  { name: "Doritos Cheese Supreme 170g", price: 4.50, category: "Snacks" },
  { name: "Pringles Original 134g", price: 4.00, category: "Snacks" },
  { name: "Rice Crackers 100g", price: 2.50, category: "Snacks" },
  { name: "Trail Mix 400g", price: 7.00, category: "Snacks" },
  { name: "Almonds Natural 400g", price: 9.00, category: "Snacks" },
  { name: "Popcorn Microwave 3pk", price: 4.50, category: "Snacks" },
  { name: "Chocolate Block Cadbury 180g", price: 5.00, category: "Snacks" },
  { name: "Chocolate Block Lindt 100g", price: 4.50, category: "Snacks" },
  { name: "Mars Bar 4pk", price: 5.00, category: "Snacks" },
  { name: "Muesli Bar 6pk", price: 4.00, category: "Snacks" },
  { name: "Protein Bar Each", price: 3.50, category: "Snacks" },
  { name: "Hummus 200g", price: 3.50, category: "Snacks" },
  { name: "Tzatziki 200g", price: 3.50, category: "Snacks" },
  { name: "Salsa 300g", price: 3.50, category: "Snacks" },
  { name: "Corn Chips 230g", price: 4.00, category: "Snacks" },

  // Frozen
  { name: "Frozen Pizza Margherita", price: 6.00, category: "Frozen" },
  { name: "Frozen Pizza Pepperoni", price: 6.50, category: "Frozen" },
  { name: "Frozen Chips Straight Cut 1kg", price: 4.00, category: "Frozen" },
  { name: "Frozen Chips Crinkle Cut 1kg", price: 4.00, category: "Frozen" },
  { name: "Frozen Mixed Vegetables 1kg", price: 3.50, category: "Frozen" },
  { name: "Frozen Peas 1kg", price: 3.00, category: "Frozen" },
  { name: "Frozen Spinach 500g", price: 3.00, category: "Frozen" },
  { name: "Frozen Berries Mixed 500g", price: 6.00, category: "Frozen" },
  { name: "Ice Cream Vanilla 1L", price: 6.00, category: "Frozen" },
  { name: "Ice Cream Connoisseur 1L", price: 10.00, category: "Frozen" },
  { name: "Ben & Jerry's 458ml", price: 12.50, category: "Frozen" },
  { name: "Frozen Nuggets 1kg", price: 8.00, category: "Frozen" },
  { name: "Frozen Fish Fillets 400g", price: 7.00, category: "Frozen" },
  { name: "Frozen Dumplings 750g", price: 8.00, category: "Frozen" },
  { name: "Frozen Dim Sims 24pk", price: 7.00, category: "Frozen" },
  { name: "Ice Blocks 8pk", price: 5.00, category: "Frozen" },

  // Household
  { name: "Toilet Paper 24pk", price: 12.00, category: "Household" },
  { name: "Toilet Paper 12pk", price: 7.50, category: "Household" },
  { name: "Paper Towels 6pk", price: 6.00, category: "Household" },
  { name: "Tissues 3pk", price: 4.00, category: "Household" },
  { name: "Cling Wrap 30m", price: 3.50, category: "Household" },
  { name: "Alfoil 10m", price: 3.00, category: "Household" },
  { name: "Baking Paper 5m", price: 3.50, category: "Household" },
  { name: "Bin Bags Large 20pk", price: 5.00, category: "Household" },
  { name: "Bin Bags Kitchen 50pk", price: 6.00, category: "Household" },
  { name: "Ziplock Bags Medium 25pk", price: 4.00, category: "Household" },

  // Cleaning
  { name: "Dish Soap 500ml", price: 3.50, category: "Cleaning" },
  { name: "Dishwasher Tablets 52pk", price: 14.00, category: "Cleaning" },
  { name: "Laundry Detergent 2L", price: 12.00, category: "Cleaning" },
  { name: "Laundry Pods 28pk", price: 14.00, category: "Cleaning" },
  { name: "Fabric Softener 1L", price: 5.00, category: "Cleaning" },
  { name: "Surface Spray 500ml", price: 4.00, category: "Cleaning" },
  { name: "Bleach 2L", price: 4.00, category: "Cleaning" },
  { name: "Sponges 5pk", price: 3.00, category: "Cleaning" },
  { name: "Steel Wool 10pk", price: 3.00, category: "Cleaning" },
  { name: "Floor Cleaner 750ml", price: 5.00, category: "Cleaning" },
  { name: "Glass Cleaner 500ml", price: 4.00, category: "Cleaning" },
  { name: "Bathroom Cleaner 500ml", price: 5.00, category: "Cleaning" },

  // Personal Care
  { name: "Shampoo 400ml", price: 6.00, category: "Personal" },
  { name: "Conditioner 400ml", price: 6.00, category: "Personal" },
  { name: "Body Wash 500ml", price: 5.50, category: "Personal" },
  { name: "Hand Soap 250ml", price: 3.00, category: "Personal" },
  { name: "Hand Sanitiser 500ml", price: 5.00, category: "Personal" },
  { name: "Toothpaste 110g", price: 4.00, category: "Personal" },
  { name: "Deodorant Spray 250ml", price: 5.50, category: "Personal" },
  { name: "Sunscreen SPF50 200ml", price: 10.00, category: "Personal" },
];
